#DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwtdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1997

#log sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
